class script(object):
    START_TXT = """🖐🏻🤓Hɪ ʜᴇʟʟᴏ {},\n\n🤹Aᴍ 𝗨𝗠𝗥 Gʀᴏᴜᴘ ᴍᴏᴠɪᴇs ᴅᴏɴᴇʀ ʀᴏʙᴏᴛ 🦸🏼‍♀️\n👼Mʏ ɴᴀᴍᴇ ɪs <a href='https://t.me/DB_MVDONER_BOT'>𝐃𝐁 𝙸𝙽𝙵𝙸𝙽𝙸𝚃𝚈 𝙼𝙾𝚅𝙸𝙴𝚂 𝙳𝙾𝙽𝙴𝚁 𝙱𝙾𝚃</a>\n\n✨𝙵𝚄𝙴𝚃𝚄𝚁𝙴𝚂 :>\n⭓ ɪ ᴄᴀɴ ʜᴇʟᴘ ᴜ ᴛᴏ sᴇᴀʀᴄʜ ᴍᴏᴠɪᴇs ɪɴ ᴍʏ ᴘᴍ.🔍\n⭓ ɪ ᴄᴀɴ ɢɪᴠᴇ ᴅɪʀᴇᴄᴛ ғɪʟᴇ ʟɪɴᴋ ɪɴ Yᴏᴜʀ ɢʀᴏᴜᴘ.📂\n⭓ ɪ ᴄᴀɴ ɢɪᴠᴇ ᴜ ɪɴғᴏ ᴏғ ᴀɴʏ ᴍᴏᴠɪᴇs.ℹ️\nAɴᴅ ᴍᴀɴʏ ᴇxᴀʟᴇɴᴛ ғᴇᴀᴛᴜʀs ......🧾\n\n⚡Jᴜsᴛ ᴀᴅᴅ ᴍᴇ ᴛᴏ ᴜʀs ɢʀᴏᴜᴘ ᴏᴋᴋ ⚡\n\n✯ Cʀᴇᴀᴛᴇʀ : <a href='https://t.me/DEEKS_04_8'> Dᴇᴇᴋsʜɪᴛʜ ɢᴏᴡᴅᴀ🦸🏼‍♀️</a>"""
    HELP_TXT = """🔰Dᴇᴀʀ {}\n\n☺️Cʜᴇᴄᴋ ᴛʜᴇ ʙᴇʟᴏᴡ ɢɪᴠᴇɴ ғᴇᴀᴜᴛᴜʀs ᴄᴏᴍᴍᴀɴᴅs👇🏻\nRᴇᴀᴅ ᴄᴀʀᴇғᴜʟʟʏ ᴏᴋᴋ..😜"""
    ABOUT_TXT = """📖𝗔𝗕𝗢𝗨𝗧 𝗠𝗘 :\n\n✯ Mʏ ɴᴀᴍᴇ : 𝗨𝗠𝗥 Gʀᴏᴜᴘ ᴍᴏᴠɪᴇs ᴅᴏɴᴇʀ ʀᴏʙᴏᴛ 🦸🏼‍♀️\n✯ Cʀᴇᴀᴛᴇʀ : <a href='https://t.me/DEEKS_04_8'>® Dᴇᴇᴋsʜɪᴛʜ ɢᴏᴡᴅᴀ</a>\n✯ Lɪʙᴇᴀʀʏ : ᴘʏʀᴏɢʀᴀᴍ\n✯ Lᴀɴɢᴜᴀɢᴇ : ᴘʏᴛʜᴏɴ 𝟹\n✯ Dᴀᴛᴀʙᴀsᴇ : ᴍᴏɴɢᴏ ᴅʙ\n✯ ʙᴏᴛ sᴇʀᴠᴇʀ : ʜᴇʀᴏᴋᴜ \n✯ ʙᴜɪʟᴅ ᴠᴇʀsɪᴏɴ : v1.0.1 [ 𝙱𝙴𝚃𝙰 ]"""
    SOURCE_TXT = """🔰 𝐂𝐇𝐀𝐍𝐍𝐄𝐋𝐒 𝐋𝐈𝐒𝐓'𝐒 :🎒\n\n✯ Mᴀɪɴ ᴄʜᴀɴɴᴇʟ : @UNI_MOVIES_BOX\n✯ Mᴀɪɴ ɢʀᴏᴜᴘ : @UM_REQUESTS\n✯ Kᴀɴɴᴀᴅᴀ ᴄʜᴀɴɴᴇʟ : @UMR_KAN_MOVIES\n✯ Fᴜᴛᴜʀᴇ ᴄʜᴀɴɴᴇʟ : @UMR_FILMBOX\n✯ Bᴏᴛ's ᴄʜᴀɴɴᴇʟ : @DB_ROBOTS\n✯ Bᴏᴛ's ɢʀᴏᴜᴘ : @DB_HELPER\n\n✯ Cʀᴇᴀᴛᴇʀ : <a href='https://t.me/DEEKS_04_8'> Dᴇᴇᴋsʜɪᴛʜ ɢᴏᴡᴅᴀ🦸🏼‍♀️</a>"""
    MANUELFILTER_TXT = """🔰𝐀𝐁𝐎𝐔𝐓 𝐒𝐀𝐌𝐏𝐋𝐄 𝐅𝐈𝐋𝐓𝐄𝐑 ✨:\n\n📯Fɪʟᴛᴇʀ Is Tʜᴇ Fᴇᴀᴛᴜʀᴇ Wᴇʀᴇ Usᴇʀs Cᴀɴ Sᴇᴛ Aᴜᴛᴏᴍᴀᴛᴇᴅ Rᴇᴘʟɪᴇs Fᴏʀ A Pᴀʀᴛɪᴄᴜʟᴀʀ Kᴇʏᴡᴏʀᴅ Aɴᴅ Iᴛ Wɪʟʟ Rᴇsᴘᴏɴᴅ Wʜᴇɴᴇᴠᴇʀ A Kᴇʏᴡᴏʀᴅ Is Fᴏᴜɴᴅ Tʜᴇ Mᴇssᴀɢᴇ ᴏᴋᴋ\n\n📝ΝϴͲᎬ :\n1. ᴜ sʜᴏᴜʟᴅ ᴀᴅᴅ ᴍᴇ ᴀs ᴀᴅᴍɪɴ ɪɴ ᴜʀs ɢʀᴏᴜᴘ.🤹\n2. ᴏɴʟʏ ᴀᴅᴍɪɴs ᴄᴀɴ ᴀᴅᴅ ғɪʟᴛᴇʀs ɪɴ ᴀ ᴄʜᴀᴛ.🤗\n3. ᴀʟᴇʀᴛ ʙᴜᴛᴛᴏɴs ʜᴀᴠᴇ ᴀ ʟɪᴍɪᴛ ᴏғ 64 ᴄʜᴀʀᴀᴄᴛᴇʀs.🤔 \n\n🔰ᏟϴᎷᎷᎪΝᎠՏ ᎪΝᎠ ႮՏᎪᏀᎬ: \n\n• /filter - ᴀᴅᴅ ᴀ ғɪʟᴛᴇʀ ɪɴ ᴄʜᴀᴛ ⭐\n• /filters - ʟɪsᴛ ᴀʟʟ ᴛʜᴇ ғɪʟᴛᴇʀs ᴏғ ᴀ ᴄʜᴀᴛ 🌠\n• /del - ᴅᴇʟᴇᴛᴇ ᴀ sᴘᴇᴄɪғɪᴄ ғɪʟᴛᴇʀ ɪɴ ᴄʜᴀᴛ 🗳️\n• /delall - ᴅᴇʟᴇᴛᴇ ᴛʜᴇ ᴡʜᴏʟᴇ ғɪʟᴛᴇʀs ɪɴ ᴀ ᴄʜᴀᴛ (ᴄʜᴀᴛ ᴏᴡɴᴇʀ ᴏɴʟʏ)🚫 \n\n✯ Cʀᴇᴀᴛᴇʀ : <a href='https://t.me/DEEKS_04_8'> Dᴇᴇᴋsʜɪᴛʜ ɢᴏᴡᴅᴀ🔰</a>"""
    BUTTON_TXT = """♻️Hᴏᴡ ᴛᴏ ᴄʀᴇᴀᴛᴇ ʙᴜᴛᴛᴏɴ ᴛᴇxᴛ ?\n\n<b>Bᴜᴛᴛᴏɴs ⌨️</b>- Tʜɪs ʙᴏᴛ sᴜᴘᴘᴏʀᴛs ʙᴏᴛʜ ᴜʀʟ ᴀɴᴅ ᴀʟᴇʀᴛ ɪɴʟɪɴᴇ ʙᴜᴛᴛᴏɴs .🏷️\n\n<b>📝ΝϴͲᎬ :</b>\n1. Tᴇʟᴇɢʀᴀᴍ Wɪʟʟ Nᴏᴛ Aʟʟᴏᴡs Yᴏᴜ Tᴏ Sᴇɴᴅ Bᴜᴛᴛᴏɴs Wɪᴛʜᴏᴜᴛ Aɴʏ Cᴏɴᴛᴇɴᴛ, Sᴏ Cᴏɴᴛᴇɴᴛ Is Mᴀɴᴅᴀᴛᴏʀʏ🧾.\n2🧾 I Sᴜᴘᴘᴏʀᴛs Bᴜᴛᴛᴏɴs Wɪᴛʜ Aɴʏ Tᴇʟᴇɢʀᴀᴍ Mᴇᴅɪᴀ Tʏᴘᴇ.📼\n3. Bᴜᴛᴛᴏɴs Sʜᴏᴜʟᴅ Bᴇ Pʀᴏᴘᴇʀʟʏ Pᴀʀsᴇᴅ As Mᴀʀᴋᴅᴏᴡɴ Fᴏʀᴍᴀᴛ.🎟️4. <b>Uʀʟ Bᴜᴛᴛᴏɴs :</b><code>[Button Text](buttonurl:https//t.me/DB_ROBOTS)</code>\n5. <b>Aʟᴇʀᴛ Bᴜᴛᴛᴏɴs :</b><code>[Button Text](buttonalert:This is an alert message)</code>♻️\n\n✯ Cʀᴇᴀᴛᴇʀ : <a href='https://t.me/DEEKS_04_8'> Dᴇᴇᴋsʜɪᴛʜ ɢᴏᴡᴅᴀ🦸🏼‍♀️</a>"""
    AUTOFILTER_TXT = """<b>🗄️𝐀𝐁𝐎𝐔𝐓 𝐀𝐔𝐓𝐎 𝐅𝐈𝐋𝐓𝐄𝐑🗑️</b>\n\n<b>📝ΝϴͲᎬ: </b>\n1. Mᴀᴋᴇ Mᴇ Tʜᴇ Aᴅᴍɪɴ Oғ Yᴏᴜʀ Cʜᴀɴɴᴇʟ Iғ Iᴛ's Pʀɪᴠᴀᴛᴇ.👑\n2. Mᴀᴋᴇ Sᴜʀᴇ Tʜᴀᴛ Yᴏᴜʀ Cʜᴀɴɴᴇʟ Dᴏᴇs Nᴏᴛ Cᴏɴᴛᴀɪɴs Cᴀᴍ Rɪᴘ, Pᴏʀɴ Aɴᴅ Fᴀᴋᴇ Fɪʟᴇs.🗜️\n3. Fᴏʀᴡᴀʀᴅ Tʜᴇ Lᴀsᴛ Mᴇssᴀɢᴇ Tᴏ Mᴇ Wɪᴛʜ Qᴜᴏᴛᴇs. I'ʟʟ Aᴅᴅ Aʟʟ Tʜᴇ Fɪʟᴇs Iɴ Tʜᴀᴛ Cʜᴀɴɴᴇʟ Tᴏ Mʏ Dʙ 🧲.\n\n✯ Cʀᴇᴀᴛᴇʀ : <a href='https://t.me/DEEKS_04_8'> Dᴇᴇᴋsʜɪᴛʜ ɢᴏᴡᴅᴀ🦸🏼‍♀️</a>"""
    CONNECTION_TXT = """<b>📢𝐀𝐁𝐎𝐔𝐓 𝐂𝐎𝐍𝐍𝐄𝐂𝐓𝐈𝐎𝐍𝐒🗳️</b>\n\n- Usᴇᴅ Tᴏ Cᴏɴɴᴇᴄᴛ Bᴏᴛ Tᴏ Pᴍ Fᴏʀ Mᴀɴᴀɢɪɴɢ Fɪʟᴛᴇʀs 🔔\n- Iᴛ Hᴇʟᴘs Tᴏ Aᴠᴏɪᴅ Sᴘᴀᴍᴍɪɴɢ Iɴ Gʀᴏᴜᴘs. 🚯\n<b>📝NOTE:</b>\n1. Oɴʟʏ Aᴅᴍɪɴs Cᴀɴ Aᴅᴅ A Cᴏɴɴᴇᴄᴛɪᴏɴ.🛡️\n2. Sᴇɴᴅ  <code>/connect</code> Fᴏʀ Cᴏɴɴᴇᴄᴛɪɴɢ Mᴇ Tᴏ Uʀ Pᴍ 📲\n\n<b>🔰𝖢𝖮𝖬𝖬𝖠𝖭𝖣𝖲 𝖠𝖭𝖣 𝖴𝖲𝖠𝖦𝖤🔰</b>\n• /connect - <code>Cᴏɴɴᴇᴄᴛ A Pᴀʀᴛɪᴄᴜʟᴀʀ Cʜᴀᴛ Tᴏ Yᴏᴜʀ Pᴍ☑️ </code>\n• /disconnect - <code>Dɪsᴄᴏɴɴᴇᴄᴛ Fʀᴏᴍ A Cʜᴀᴛ❎ </code>\n• /connections - <code>Lɪsᴛ Aʟʟ Yᴏᴜʀ Cᴏɴɴᴇᴄᴛɪᴏɴs📜 </code>\n\n✯ Cʀᴇᴀᴛᴇʀ : <a href='https://t.me/DEEKS_04_8'> Dᴇᴇᴋsʜɪᴛʜ ɢᴏᴡᴅᴀ🦸🏼‍♀️</a>"""
    EXTRAMOD_TXT = """<b>🔮𝐀𝐁𝐎𝐔𝐓 𝐄𝐗𝐓𝐑𝐀 𝐌𝐎𝐃𝐔𝐋𝐄𝐒🔖</b>\n\n<b>📝NOTE:</b>Tʜᴇsᴇ Aʀᴇ Tʜᴇ Exᴛʀᴀ Fᴇᴀᴛᴜʀᴇs Oғ Tʜɪs Bᴏᴛ 📑\n\n<b>𝙲𝙾𝙼𝙼𝙰𝙽𝙳𝚂 𝙰𝙽𝙳 𝚄𝚂𝙰𝙶𝙴🧰:</b>\n\n• /id - <code>Gᴇᴛ Iᴅ Oғ A Sᴘᴇᴄɪғᴇᴅ Usᴇʀ🆔 .</code>\n• /info - <code>Gᴇᴛ Iɴғᴏʀᴍᴀᴛɪᴏɴ Aʙᴏᴜᴛ A Usᴇʀ .ℹ️</code>\n• /imdb - <code>Gᴇᴛ Tʜᴇ Fɪʟᴍ Iɴғᴏʀᴍᴀᴛɪᴏɴ Fʀᴏᴍ Iᴍᴅʙ Sᴏᴜʀᴄᴇ .✔️</code>\n• /search - <code>Gᴇᴛ Tʜᴇ Fɪʟᴍ Iɴғᴏʀᴍᴀᴛɪᴏɴ Fʀᴏᴍ Vᴀʀɪᴏᴜs Sᴏᴜʀᴄᴇs 〽️.</code>\n\n✯ Cʀᴇᴀᴛᴇʀ : <a href='https://t.me/DEEKS_04_8'> Dᴇᴇᴋsʜɪᴛʜ ɢᴏᴡᴅᴀ🦸🏼‍♀️</a>"""
    ADMIN_TXT = """🔮𝐀𝐁𝐎𝐔𝐓 𝐀𝐃𝐌𝐈𝐍 𝐌𝐎𝐃𝐄𝐒👷\n\n📝𝖭𝖮𝖳𝖤:Tʜɪs Mᴏᴅᴜʟᴇ Oɴʟʏ Wᴏʀᴋs Fᴏʀ Mʏ Aᴅᴍɪɴs 💣\n\n<u>𝙲𝙾𝙼𝙼𝙰𝙽𝙳𝚂 𝙰𝙽𝙳 𝚄𝚂𝙰𝙶𝙴:🗝️</u>\n• /logs - Tᴏ Gᴇᴛ Tʜᴇ Rᴇsᴄᴇɴᴛ Eʀʀᴏʀs 🌐\n• /stats - Tᴏ Gᴇᴛ Sᴛᴀᴛᴜs Oғ Fɪʟᴇs Iɴ Dʙ .🏧\n• /users - Tᴏ Gᴇᴛ Lɪsᴛ Oғ Mʏ Usᴇʀs Aɴᴅ Iᴅs. 👥\n• /chats - Tᴏ Gᴇᴛ Lɪsᴛ Oғ Tʜᴇ Mʏ Cʜᴀᴛs Aɴᴅ Iᴅs  ♨️\n• /leave  - Tᴏ Lᴇᴀᴠᴇ Fʀᴏᴍ A Cʜᴀᴛ .⛔\n• /disable  - Dᴏ Dɪsᴀʙʟᴇ A Cʜᴀᴛ .🚫\n• /ban  - Tᴏ Bᴀɴ A Usᴇʀ 🔒\n• /unban  - Tᴏ Uɴʙᴀɴ A Usᴇʀ .🔓\n• /channel - Tᴏ Gᴇᴛ Lɪsᴛ Oғ Tᴏᴛᴀʟ Cᴏɴɴᴇᴄᴛᴇᴅ Cʜᴀɴɴᴇʟs 📢\n• /broadcast - Tᴏ Bʀᴏᴀᴅᴄᴀsᴛ A Mᴇssᴀɢᴇ Tᴏ Aʟʟ Usᴇʀs 📣\n\n✯ Cʀᴇᴀᴛᴇʀ : <a href='https://t.me/DEEKS_04_8'> Dᴇᴇᴋsʜɪᴛʜ ɢᴏᴡᴅᴀ🦸🏼‍♀️</a>"""
    STATUS_TXT = """🗄️𝗕𝗢𝗧'𝗦 𝗦𝗧𝗔𝗧𝗨𝗦📊\n\n⭓ Tᴏᴛᴀʟ ғɪʟᴇs sᴀᴠᴇᴅ : <code>{}</code>📩\n⭓ Tᴏᴛᴀʟ ᴜsᴇʀs ᴜsɪɴɢ : <code>{}</code>👬\n⭓ Tᴏᴛᴀʟ ᴄᴏɴɴᴇᴄᴛᴇᴅ ᴄʜᴀᴛs : <code>{}</code>📮\n⭓ Usᴇᴅ sᴛᴏʀᴀɢᴇ : <code>{}</code> ᴍʙ's📲\n⭓ Fʀᴇᴇ sᴛᴏʀᴀɢᴇ : <code>{}</code> ᴍʙ's📱\n\n✯ Cʀᴇᴀᴛᴇʀ : <a href='https://t.me/DEEKS_04_8'> Dᴇᴇᴋsʜɪᴛʜ ɢᴏᴡᴅᴀ🦸🏼‍♀️</a>"""
    LOG_TEXT_G = """#NewGroup
Group = {}(<code>{}</code>)
Total Members = <code>{}</code>
Added By - {}
"""
    LOG_TEXT_P = """#NewUser
ID - <code>{}</code>
Name - {}
"""
